# Generated by Django 3.2.5 on 2021-07-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name_department', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('date_of_birthday', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_app.department')),
            ],
        ),
    ]
