# Generated by Django 3.2.5 on 2021-07-26 07:06

from django.db import migrations


def data_for_db(apps, schema_editor):
    Department = apps.get_model('department_app', 'Department')
    Department.objects.bulk_create([
        Department(id=1, name='Management'),
        Department(id=2, name='Developing'),
        Department(id=3, name='Testing'),
        Department(id=4, name='Bookkeeping')
    ])
    Employee = apps.get_model('department_app', 'Employee')
    Employee.objects.bulk_create([
        Employee(name='Peter Panov', date_of_birthday='1994-07-04', salary=1300.00,
                 department=Department.objects.get(id=1)),
        Employee(name='Henri Holland', date_of_birthday='2000-02-05', salary=900.09,
                 department=Department.objects.get(id=1)),
        Employee(name='Olga Erganova', date_of_birthday='1994-05-01', salary=1150.18,
                 department=Department.objects.get(id=2)),
        Employee(name='Frank Cabo', date_of_birthday='1998-03-12', salary=941.00,
                 department=Department.objects.get(id=3)),
        Employee(name='Ivan Ivanov', date_of_birthday='1996-01-12', salary=922.00,
                 department=Department.objects.get(id=4)),
    ])


def delete_data(apps, schema_editor):
    Department = apps.get_model('department_app', 'Department')
    Department.objects.filter(id=1, name='Management').delete()
    Department.objects.filter(id=2, name='Developing').delete()
    Department.objects.filter(id=3, name='Testing').delete()
    Department.objects.filter(id=4, name='Bookkeeping').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('department_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(data_for_db, delete_data)
    ]
