# Generated by Django 3.2.5 on 2021-07-26 07:06

from django.db import migrations


def data_for_db(apps, schema_editor):
    Department = apps.get_model('department_app', 'Department')
    Department.objects.bulk_create([
        Department(name_department='Management'),
        Department(name_department='Developing'),
        Department(name_department='Testing'),
        Department(name_department='Bookkeeping')
    ])
    Employee = apps.get_model('department_app', 'Employee')
    Employee.objects.bulk_create([
        Employee(name='Peter Panov', date_of_birthday='1994-07-04', salary=1300.00,
                 id_department=Department.objects.get(name_department='Management')),
        Employee(name='Henri Holland', date_of_birthday='2000-02-05', salary=900.09,
                 id_department=Department.objects.get(name_department='Management')),
        Employee(name='Olga Erganova', date_of_birthday='1994-05-01', salary=1150.18,
                 id_department=Department.objects.get(name_department='Developing')),
        Employee(name='Frank Cabo', date_of_birthday='1998-03-12', salary=941.00,
                 id_department=Department.objects.get(name_department='Testing')),
        Employee(name='Ivan Ivanov', date_of_birthday='1996-01-12', salary=922.00,
                 id_department=Department.objects.get(name_department='Bookkeeping')),
    ])


def delete_data(apps, schema_editor):
    Department = apps.get_model('department_app', 'Department')
    Department.objects.filter(name_department='Management').delete()
    Department.objects.filter(name_department='Developing').delete()
    Department.objects.filter(name_department='Testing').delete()
    Department.objects.filter(name_department='Bookkeeping').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('department_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(data_for_db, delete_data)
    ]
