# Generated by Django 3.2.5 on 2021-07-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0003_auto_20210726_1012'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
    ]
