# Generated by Django 3.2.5 on 2021-08-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0004_auto_20210726_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
