# Generated by Django 3.2.5 on 2021-08-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0005_alter_department_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name_d'], 'verbose_name': 'Department names'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name_e'], 'verbose_name': 'Employee information'},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='name_d',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='name_e',
        ),
    ]
