# Generated by Django 3.2.5 on 2021-08-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0006_auto_20210811_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['full_name'], 'verbose_name': 'Department names'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'verbose_name': 'Employee information'},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name_d',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name_e',
            new_name='full_name',
        ),
    ]
